flags: {}
packages:
- '.'
extra-deps:
- MonadRandom-0.4.1
- ansi-terminal-0.6.2.3
- ansi-wl-pprint-0.6.7.3
- base-orphans-0.4.4
- bifunctors-5.1
- clock-0.5.1
- comonad-4.2.7.2
- contravariant-1.3.3
- distributive-0.4.4
- either-4.4.1
- errors-2.0.1
- event-list-0.1.1.2
- explicit-exception-0.1.7.3
- free-4.12.1
- midi-0.2.1.5
- mmorph-1.0.4
- monad-control-1.0.0.4
- monoid-transformer-0.0.3
- non-negative-0.1.1
- optparse-applicative-0.12.0.0
- prelude-extras-0.4.0.2
- profunctors-5.1.1
- regex-tdfa-rc-1.1.8.3
- safe-0.3.9
- semigroupoids-5.0.0.4
- semigroups-0.18.0.1
- tagged-0.8.2
- tasty-0.11.0.1
- tasty-hunit-0.9.2
- tasty-quickcheck-0.8.4
- transformers-base-0.4.4
- unbounded-delays-0.1.0.9
- utility-ht-0.0.11
- void-0.7.1
resolver: ghc-7.10.2
